name: "Website build"

on: ["push", "pull_request"]

env:
  doctrine_website_github_http_token: "${{ github.token }}"
  PHP_VERSION: "7.2"
  doctrine_website_mysql_password: "${{ secrets.doctrine_website_mysql_password }}"
  doctrine_website_algolia_admin_api_key: "no-key-needed"

jobs:
  tests:

    runs-on: "ubuntu-18.04"

    services:
      mysql:
        image: "mysql:5.7"
        env:
          MYSQL_DATABASE: "doctrine_website_test"
          MYSQL_ROOT_PASSWORD: "${{ secrets.doctrine_website_mysql_password }}"
        ports:
          - "3306:3306"

    steps:
    - uses: "actions/checkout@v2"

    - name: "Setup PHP Action"
      uses: "shivammathur/setup-php@v2"
      with:
        php-version: "${{ env.PHP_VERSION }}"
        coverage: "none"

    - name: "Install dependencies with Composer"
      uses: "ramsey/composer-install@v1"
      with:
        composer-options: "--prefer-dist --no-progress --no-suggest"

    - name: "Installation of node"
      uses: "actions/setup-node@v2"
      with:
        node-version: '10.22.0'

    - name: "yarn install"
      uses: "borales/actions-yarn@v2.0.0"
      with:
        cmd: "install"

    - name: "Run tests"
      run: "./vendor/bin/phpunit"

    - name: "Setup PHP Action"
      uses: "shivammathur/setup-php@v2"
      with:
        php-version: "${{ env.PHP_VERSION }}"
        coverage: "pcov"

    - name: "Build website"
      run: "./bin/console --env=test build-all"

    - name: "Run tests with coverage"
      run: "./vendor/bin/phpunit --coverage-clover clover.xml"

    - name: "Deliver code coverage"
      run: "bash <(curl -s https://codecov.io/bash)"
